<a href="https://colab.research.google.com/github/nilkanthmate2/Adeventure-2/blob/main/Exeperiment_13_2201645_NOTEBOOK1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MINI PROJECT: House Price Prediction**

# **NOTEBOOK 1: Data Selection, Cleaning & Wrangling**
🔹 1. Import Libraries

In [2]:
import pandas as pd
import numpy as np

🔹 2. Load Dataset

In [4]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

🔹 3. Data Selection (Write Explanation)

👉 Dataset: House Price Dataset
👉 Target Variable: SalePrice
👉 Problem Type: Regression

👉 Reason:

Predict continuous values (price)

👉 Dataset: California Housing Dataset
👉 Target Variable: median_house_value
👉 Problem Type: Regression

👉 Reason:

Predict continuous values (house price)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

🔹 4. Attribute Description

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

Here are the attributes for the `california_housing_train.csv` dataset:

*   `longitude`: A measure of how far west a house is located; a higher value is farther west.
*   `latitude`: A measure of how far north a house is located; a higher value is farther north.
*   `housing_median_age`: Median age of a house within a block; a lower number is a newer building.
*   `total_rooms`: Total number of rooms within a block.
*   `total_bedrooms`: Total number of bedrooms within a block.
*   `population`: Total number of people residing within a block.
*   `households`: Total number of households, a group of people residing within a home unit.
*   `median_income`: Median income for households within a block (measured in tens of thousands of US Dollars).
*   `median_house_value`: Median house value for households within a block (measured in US Dollars). This is the **target variable** for our regression problem.

👉 Reason:

Too many missing values

Example explanation:

LotArea → Numeric
OverallQual → Integer (quality rating)
YearBuilt → Integer
SalePrice → Target variable

🔹 5. Handle Missing Values

In [8]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

🔹 6. Drop Unnecessary Columns

In [11]:
# No unnecessary columns to drop in this dataset based on initial inspection.

In [13]:
# Based on the current dataset, there are no unnecessary columns to drop after checking df.info() and df.isnull().sum().

🔹 7. Encoding Categorical Data

In [14]:
df = pd.get_dummies(df)

🔹 8. Save Clean Data

In [15]:
df.to_csv("cleaned_house_price.csv", index=False)